server:
  port: ${PORT:0}
  context-path: /api

management:
  context-path: /manage

endpoints:
    enabled: false
    info.enabled: true
    health.enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  datasource:
    url: jdbc:h2:~/tmp/db:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:


---
# For deployment in Docker containers
spring:
  profiles: docker
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:h2:/app/db:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: false

server:
  port: 8080


---
# local stand alone development
spring:
  profiles: development
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:h2:~/tmp/db:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console



server:
  port: 8080
